### ISSUE TITLE
Add constants support

### ISSUE THREAD

**Issue by XaosSintez** [Rebilly/RebillyAPI#34]
We need some constants support here:
https://github.com/Rebilly/RebillyAPI/pull/33
Otherwise we have to put big block in every path

**Comment by RomanGotsiy** [comment]
I decided to add global `headers`. During build references to headers will be inlined and global `headers` will be removed so spec will be valid.

@XaosSintez to use this feature update swagger-repo tool: `npm update swagger-repo` and procced with the approach from [this commit](https://github.com/Rebilly/RebillyAPI/pull/33/commits/6bfb8d748b98c54cddd37099a0b0c2358f7c5911)

but don't use array - response headers should be an object:
**before:**
```yaml
headers:		
  - $ref: "#/headers/X-Rate-Limit-Limit"
```
**after:**
```yaml
headers:	
  X-Rate-Limit-Limit:
    $ref: "#/headers/X-Rate-Limit-Limit"
```

P.S. Only simple references are supported. You can't use `allOf`

**Comment by slavcodev** [comment]
👎  AFAIU, it is against to swagger standard, so the main questions, what is our goal? Follow the swagger spec, or allow hacks? :)

**Comment by slavcodev** [comment]
I wonder if this will work

```yaml
responses:
  BaseResponse:
    headers: [rate-limiting, etc]
  CollectionResponse:
    allOf:
      - $ref: "#/responses/BaseResponse"
      - params: [filter, sort, etc]
paths:
  /customers
    get:
      responses:
        200:
          allOf:
            - $ref: "#/responses/CollectionResponse"
```

**Comment by IvanGoncharov** [comment]
> AFAIU, it is against to swagger standard, so the main questions, what is our goal?

@slavcodev Idea is to resolve headers at the pre-processing step to generate valid Swagger.
`spec/swagger.yaml` isn't valid Swagger because it has empty `paths`, moreover, it doesn't represent Rebilly API. But after build step, it's complete and 100% standard compliant Swagger file.

We probably need to remove `swagger: 2.0` as the first line and it as part of the build process.
To prevent confusion from people trying to use `spec/swagger.yaml` as valid Swagger.

> I wonder if this will work

No, you can use `allOf` only inside `schema` property and array should consist only of JSON schemas or references to them.

**Comment by slavcodev** [comment]
That's make sense. Thanks 👍

**Comment by XaosSintez** [comment]
It worked perfectly, thanks
